baseurl: /lokaverkefni
collections:
  tonlistarmen:
    output: true
defaults:
  - scope:
      path: ""
    values: 
      layout: "default" 

  - scope:
      path: ""
      type: "tonlistarmen"
    values: 
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass: 
  style: compressed